services:
  - docker

env:
  global:
    - DOCKER_REPO="oanhnn/php"
  matrix:
    - IMAGE_TAG="7.1-cli-alpine"
    - IMAGE_TAG="7.2-cli-alpine"
    - IMAGE_TAG="7.1-fpm-alpine"
    - IMAGE_TAG="7.2-fpm-alpine"
    - IMAGE_TAG="7.1-alpine"
    - IMAGE_TAG="7.2-alpine"

before_script:
  - docker info
  - export BUILD_TAG=${IMAGE_TAG}
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export BUILD_VERSION=${IMAGE_TAG}
  - export VCS_REF=`git rev-parse --short HEAD`

script:
  - cd $IMAGE_TAG
  - echo "=> Building the image"
  - docker pull $DOCKER_REPO:$IMAGE_TAG || true
  - docker build --label "org.label-schema.build-date=$BUILD_DATE"
                 --label "org.label-schema.name='The PHP Docker Image'"
                 --label "org.label-schema.description='The PHP Docker Image'"
                 --label "org.label-schema.url='https://github.com/oanhnn/docker-php'"
                 --label "org.label-schema.vcs-url='https://github.com/oanhnn/docker-php.git'"
                 --label "org.label-schema.vcs-ref=$VCS_REF"
                 --label "org.label-schema.version=$BUILD_VERSION"
                 --label "org.label-schema.schema-version=1.0"
                 --cache-from $DOCKER_REPO:$IMAGE_TAG
                 --tag $DOCKER_REPO:$BUILD_TAG --pull --compress .
