services:
  - docker

env:
  global:
    - IMAGE_REPO="oanhnn/php"
  matrix:
    - IMAGE_TAG="7.1-cli-alpine"
    - IMAGE_TAG="7.2-cli-alpine"
    - IMAGE_TAG="7.1-fpm-alpine"
    - IMAGE_TAG="7.2-fpm-alpine"
    - IMAGE_TAG="7.1-alpine"
    - IMAGE_TAG="7.2-alpine"

before_script:
  - docker info
  - export IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG" CACHE_TAG="$IMAGE_TAG"

script:
  - cd $IMAGE_TAG
  - ./hooks/build
