services:
  - docker

env:
  global:
    - DOCKER_REPO="oanhnn/php"
  matrix:
    - IMAGE_TAG="7.1-cli-alpine"
    - IMAGE_TAG="7.2-cli-alpine"
    - IMAGE_TAG="7.1-fpm-alpine"
    - IMAGE_TAG="7.2-fpm-alpine"
    - IMAGE_TAG="7.1-alpine"
    - IMAGE_TAG="7.2-alpine"

before_script:
  - docker info

script:
  - cd $IMAGE_TAG
  - echo "=> Building the image"
  - docker pull $DOCKER_REPO:$IMAGE_TAG || true
  - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
                 --build-arg VCS_REF=`git rev-parse --short HEAD`
                 --build-arg VERSION=$IMAGE_TAG
                 --cache-from $DOCKER_REPO:$IMAGE_TAG
                 --tag $DOCKER_REPO:$IMAGE_TAG --pull --compress .
