services:
  - docker

env:
  global:
    - DOCKER_REPO="oanhnn/php"
  matrix:
    - VERSION=7.1 VARIANT=cli-alpine
    - VERSION=7.1 VARIANT=fpm-alpine
    - VERSION=7.1 VARIANT=alpine
    - VERSION=7.1 VARIANT=laravel
    - VERSION=7.2 VARIANT=cli-alpine
    - VERSION=7.2 VARIANT=fpm-alpine
    - VERSION=7.2 VARIANT=alpine
    - VERSION=7.2 VARIANT=laravel

before_script:
  - docker info
  - export IMAGE_NAME="oanhnn/php:${VERSION}-${VARIANT}"
  - export IMAGE_TAG="${VERSION}-${VARIANT}"
  - export CACHE_TAG="${VERSION}-${VARIANT}"

script:
  - cd $IMAGE_TAG
  - ./hooks/build
